package model;

/** Subclass of part for parts to be manufactured in-house.*/
public class InHouse extends Part {

    /** ID of in-house machine to manufacture part.*/
    private int machineId;

    /** Constructor for in-house part objects.
     @param id Unique part ID, typically auto-generated by program.
     @param name Part name.
     @param price Part price.
     @param stock Current number of part in stock.
     @param min Minimum available stock.
     @param max Maximum available stock.
     @param machineId ID of machine manufacturing part.*/
    public InHouse(int id, String name, double price, int stock, int min, int max, int machineId) {
        super(id, name, price, stock, min, max);
        this.machineId = machineId;
    }

    /** Sets ID of machine manufacturing part.*/
    public void setMachineId(int machineId) {
        this.machineId = machineId;
    }

    /** Returns ID of machine manufacturing part.*/
    public int getMachineId() {
        return machineId;
    }
}
