package model;

/** Subclass of part for parts whose manufacturing is to be outsourced.*/
public class OutSourced extends Part {

    /** Name of company to outsource part manufacturing from.*/
    private String companyName;

    /** Constructor for outsourced part objects.
     @param id Unique part ID, typically auto-generated by program.
     @param name Part name.
     @param price Part price.
     @param stock Current number of part in stock.
     @param min Minimum available stock.
     @param max Maximum available stock.
     @param companyName Name of company manufacturing part.*/
    public OutSourced(int id, String name, double price, int stock, int min, int max, String companyName) {
        super(id, name, price, stock, min, max);
        this.companyName = companyName;
    }

    /** Sets name of company manufacturing outsourced part.*/
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /** Returns name of company manufacturing outsourced part.*/
    public String getCompanyName() {
        return companyName;
    }
}
